[package]
name = "source"
version = "0.1.0"
authors = ["jakedipity <jacob.hull@logdna.com>"]
edition = "2018"

[dependencies]
#local
http = { package = "http", path = "../http" }

tokio = { version = "0.2", features = ["full"] }
async-trait = "0.1"
